/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {
var yyerrok = 0, yyclearin = 0;
...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var grammarDB = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[2,5,13,14],$V1=[1,33],$V2=[1,38],$V3=[18,29],$V4=[1,44],$V5=[8,18];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"programa":3,"lista_sentencias":4,"EOF":5,"sentencia":6,"crear_tabla":7,"PUNTO_COMA":8,"seleccionar_columna":9,"insertar_registro":10,"actualizar_registro":11,"eliminar_registro":12,"TABLA":13,"IDENTIFICADOR":14,"COLUMNAS":15,"lista_columnas":16,"columna_def":17,"COMA":18,"ASIGNACION":19,"tipo_dato":20,"TIPO_ENTERO":21,"TIPO_FLOTANTE":22,"TIPO_CADENA":23,"TIPO_BOOLEANO":24,"TIPO_CARACTER":25,"PUNTO":26,"CORCHETE_ABRE":27,"lista_asignaciones":28,"CORCHETE_CIERRA":29,"EN":30,"ENTERO":31,"BORRAR":32,"asignacion":33,"valor":34,"CADENA":35,"CARACTER":36,"DECIMAL":37,"VERDADERO":38,"FALSO":39,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",8:"PUNTO_COMA",13:"TABLA",14:"IDENTIFICADOR",15:"COLUMNAS",18:"COMA",19:"ASIGNACION",21:"TIPO_ENTERO",22:"TIPO_FLOTANTE",23:"TIPO_CADENA",24:"TIPO_BOOLEANO",25:"TIPO_CARACTER",26:"PUNTO",27:"CORCHETE_ABRE",29:"CORCHETE_CIERRA",30:"EN",31:"ENTERO",32:"BORRAR",35:"CADENA",36:"CARACTER",37:"DECIMAL",38:"VERDADERO",39:"FALSO"},
productions_: [0,[3,2],[3,2],[4,0],[4,2],[6,2],[6,2],[6,1],[6,2],[6,2],[6,2],[7,4],[7,4],[16,1],[16,3],[17,3],[20,1],[20,1],[20,1],[20,1],[20,1],[9,3],[9,3],[10,4],[10,5],[10,4],[11,6],[11,6],[12,3],[12,3],[28,1],[28,3],[33,3],[34,1],[34,1],[34,1],[34,1],[34,1],[34,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 return $$[$0-1]; 
break;
case 2:

      registrarErrorSintacticoActual('Estructura DB invalida');
      yyerrok;
      return [];
    
break;
case 3:
 this.$ = []; 
break;
case 4:
 this.$ = $$[$0-1].concat($$[$0] ? [$$[$0]] : []); return this.$; 
break;
case 5: case 6: case 8: case 9:
 this.$ = $$[$0-1]; 
break;
case 7: case 33: case 34:
 this.$ = $$[$0]; 
break;
case 10:

      registrarErrorSintacticoActual('Sentencia DB invalida');
      yyerrok;
      this.$ = null;
    
break;
case 11:
 this.$ = { tipo: 'create_table', tabla: $$[$0-2], columnas: $$[$0] }; 
break;
case 12:

      registrarErrorSintacticoActual('Creacion de tabla invalida');
      yyerrok;
      this.$ = { tipo: 'create_table', tabla: null, columnas: $$[$0] };
    
break;
case 13: case 30:
 this.$ = [$$[$0]]; 
break;
case 14: case 31:
 this.$ = $$[$0-2].concat([$$[$0]]); 
break;
case 15:
 this.$ = { nombre: $$[$0-2], tipo: $$[$0] }; 
break;
case 16:
 this.$ = 'int'; 
break;
case 17:
 this.$ = 'float'; 
break;
case 18:
 this.$ = 'string'; 
break;
case 19:
 this.$ = 'boolean'; 
break;
case 20:
 this.$ = 'char'; 
break;
case 21:
 this.$ = { tipo: 'select_column', tabla: $$[$0-2], columna: $$[$0] }; 
break;
case 22:

      registrarErrorSintacticoActual('Consulta de columna invalida');
      yyerrok;
      this.$ = { tipo: 'select_column', tabla: $$[$0-2], columna: $$[$0] };
    
break;
case 23:
 this.$ = { tipo: 'insert', tabla: $$[$0-3], valores: $$[$0-1] }; 
break;
case 24:
 this.$ = { tipo: 'insert', tabla: $$[$0-4], valores: $$[$0-2] }; 
break;
case 25:

      registrarErrorSintacticoActual('Insercion de registro invalida');
      yyerrok;
      this.$ = { tipo: 'insert', tabla: $$[$0-3], valores: [] };
    
break;
case 26:
 this.$ = { tipo: 'update', tabla: $$[$0-5], valores: $$[$0-3], id: Number($$[$0]) }; 
break;
case 27:

      registrarErrorSintacticoActual('Actualizacion de registro invalida');
      yyerrok;
      this.$ = { tipo: 'update', tabla: $$[$0-5], valores: [], id: Number($$[$0]) };
    
break;
case 28:
 this.$ = { tipo: 'delete', tabla: $$[$0-2], id: Number($$[$0]) }; 
break;
case 29:

      registrarErrorSintacticoActual('Eliminacion de registro invalida');
      yyerrok;
      this.$ = { tipo: 'delete', tabla: $$[$0-2], id: null };
    
break;
case 32:
 this.$ = { columna: $$[$0-2], valor: $$[$0] }; 
break;
case 35: case 36:
 this.$ = Number($$[$0]); 
break;
case 37:
 this.$ = true; 
break;
case 38:
 this.$ = false; 
break;
}
},
table: [o([5,13,14],[2,3],{3:1,4:2,2:[1,3]}),{1:[3]},{2:[1,11],5:[1,4],6:5,7:6,9:7,10:8,11:9,12:10,13:[1,12],14:[1,13]},{5:[1,14]},{1:[2,1]},o($V0,[2,4]),{8:[1,15]},{8:[1,16]},o($V0,[2,7]),{8:[1,17]},{8:[1,18]},{8:[1,19]},{2:[1,21],14:[1,20]},{2:[1,23],26:[1,22],27:[1,24],32:[1,25]},{1:[2,2]},o($V0,[2,5]),o($V0,[2,6]),o($V0,[2,8]),o($V0,[2,9]),o($V0,[2,10]),{15:[1,26]},{15:[1,27]},{14:[1,28]},{14:[1,29]},{2:[1,31],14:$V1,28:30,33:32},{2:[1,35],31:[1,34]},{14:$V2,16:36,17:37},{14:$V2,16:39,17:37},{8:[2,21]},{8:[2,22]},{18:[1,41],29:[1,40]},{29:[1,42]},o($V3,[2,30]),{19:[1,43]},{8:[2,28]},{8:[2,29]},{8:[2,11],18:$V4},o($V5,[2,13]),{19:[1,45]},{8:[2,12],18:$V4},o($V0,[2,23],{8:[1,46],30:[1,47]}),{14:$V1,33:48},o($V0,[2,25],{30:[1,49]}),{31:[1,54],34:50,35:[1,51],36:[1,52],37:[1,53],38:[1,55],39:[1,56]},{14:$V2,17:57},{20:58,21:[1,59],22:[1,60],23:[1,61],24:[1,62],25:[1,63]},o($V0,[2,24]),{31:[1,64]},o($V3,[2,31]),{31:[1,65]},o($V3,[2,32]),o($V3,[2,33]),o($V3,[2,34]),o($V3,[2,35]),o($V3,[2,36]),o($V3,[2,37]),o($V3,[2,38]),o($V5,[2,14]),o($V5,[2,15]),o($V5,[2,16]),o($V5,[2,17]),o($V5,[2,18]),o($V5,[2,19]),o($V5,[2,20]),{8:[2,26]},{8:[2,27]}],
defaultActions: {4:[2,1],14:[2,2],28:[2,21],29:[2,22],34:[2,28],35:[2,29],64:[2,26],65:[2,27]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse (input) {
    var self = this,
        stack = [0],
        tstack = [], // token stack
        vstack = [null], // semantic value stack
        lstack = [], // location stack
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;

    var args = lstack.slice.call(arguments, 1);

    //this.reductionCount = this.shiftCount = 0;

    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    // copy state
    for (var k in this.yy) {
      if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
        sharedState.yy[k] = this.yy[k];
      }
    }

    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);

    var ranges = lexer.options && lexer.options.ranges;

    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }

    function popStack (n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }

_token_stack:
    var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        // if token isn't its numeric value, convert
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }

    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        // retreive state number from top of stack
        state = stack[stack.length - 1];

        // use default actions if available
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            // read action for current state and first input
            action = table[state] && table[state][symbol];
        }

_handle_error:
        // handle parse error
        if (typeof action === 'undefined' || !action.length || !action[0]) {
            var error_rule_depth;
            var errStr = '';

            // Return the rule stack depth where the nearest error rule can be found.
            // Return FALSE when no error recovery rule was found.
            function locateNearestErrorRecoveryRule(state) {
                var stack_probe = stack.length - 1;
                var depth = 0;

                // try to recover from error
                for(;;) {
                    // check for error recovery rule in this state
                    if ((TERROR.toString()) in table[state]) {
                        return depth;
                    }
                    if (state === 0 || stack_probe < 2) {
                        return false; // No suitable error recovery rule available.
                    }
                    stack_probe -= 2; // popStack(1): [symbol, action]
                    state = stack[stack_probe];
                    ++depth;
                }
            }

            if (!recovering) {
                // first see if there's any chance at hitting an error recovery rule:
                error_rule_depth = locateNearestErrorRecoveryRule(state);

                // Report error
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push("'"+this.terminals_[p]+"'");
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line '+(yylineno+1)+":\n"+lexer.showPosition()+"\nExpecting "+expected.join(', ') + ", got '" + (this.terminals_[symbol] || symbol)+ "'";
                } else {
                    errStr = 'Parse error on line '+(yylineno+1)+": Unexpected " +
                                  (symbol == EOF ? "end of input" :
                                              ("'"+(this.terminals_[symbol] || symbol)+"'"));
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected,
                    recoverable: (error_rule_depth !== false)
                });
            } else if (preErrorSymbol !== EOF) {
                error_rule_depth = locateNearestErrorRecoveryRule(state);
            }

            // just recovered from another error
            if (recovering == 3) {
                if (symbol === EOF || preErrorSymbol === EOF) {
                    throw new Error(errStr || 'Parsing halted while starting to recover from another error.');
                }

                // discard current lookahead and grab another
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                symbol = lex();
            }

            // try to recover from error
            if (error_rule_depth === false) {
                throw new Error(errStr || 'Parsing halted. No suitable error recovery rule available.');
            }
            popStack(error_rule_depth);

            preErrorSymbol = (symbol == TERROR ? null : symbol); // save the lookahead token
            symbol = TERROR;         // insert generic error symbol as new lookahead
            state = stack[stack.length-1];
            action = table[state] && table[state][TERROR];
            recovering = 3; // allow 3 real symbols to be shifted before reporting a new error
        }

        // this shouldn't happen, unless resolve defaults are off
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: '+state+', token: '+symbol);
        }

        switch (action[0]) {
            case 1: // shift
                //this.shiftCount++;

                stack.push(symbol);
                vstack.push(lexer.yytext);
                lstack.push(lexer.yylloc);
                stack.push(action[1]); // push state
                symbol = null;
                if (!preErrorSymbol) { // normal execution/no error
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    if (recovering > 0) {
                        recovering--;
                    }
                } else {
                    // error just occurred, resume old lookahead f/ before error
                    symbol = preErrorSymbol;
                    preErrorSymbol = null;
                }
                break;

            case 2:
                // reduce
                //this.reductionCount++;

                len = this.productions_[action[1]][1];

                // perform semantic action
                yyval.$ = vstack[vstack.length-len]; // default to $$ = $1
                // default location, uses first token for firsts, last for lasts
                yyval._$ = {
                    first_line: lstack[lstack.length-(len||1)].first_line,
                    last_line: lstack[lstack.length-1].last_line,
                    first_column: lstack[lstack.length-(len||1)].first_column,
                    last_column: lstack[lstack.length-1].last_column
                };
                if (ranges) {
                  yyval._$.range = [lstack[lstack.length-(len||1)].range[0], lstack[lstack.length-1].range[1]];
                }
                r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));

                if (typeof r !== 'undefined') {
                    return r;
                }

                // pop off stack
                if (len) {
                    stack = stack.slice(0,-1*len*2);
                    vstack = vstack.slice(0, -1*len);
                    lstack = lstack.slice(0, -1*len);
                }

                stack.push(this.productions_[action[1]][0]);    // push nonterminal (reduce)
                vstack.push(yyval.$);
                lstack.push(yyval._$);
                // goto new state = table[STATE][NONTERMINAL]
                newState = table[stack[stack.length-2]][stack[stack.length-1]];
                stack.push(newState);
                break;

            case 3:
                // accept
                return true;
        }

    }

    return true;
}};

  
  var erroresLexicos = [];
  var erroresSintacticos = [];
  parser.erroresLexicos = erroresLexicos;
  parser.erroresSintacticos = erroresSintacticos;

  function resgistrarErrorLexico(lexema, linea, columna){
    erroresLexicos.push({
      tipo: 'lexico',
      lexema: lexema,
      linea: linea,
      columna: columna,
      mensaje: 'Token no reconocido: ' + lexema
    });
  }

  function registrarErrorSintactico(mensaje, lexema, linea, columna){
    erroresSintacticos.push({
      tipo: 'sintactico',
      lexema: lexema,
      linea: linea,
      columna: columna,
      mensaje: mensaje
    });
  }

  function registrarErrorSintacticoActual(mensaje){
    var linea = (typeof yylloc !== 'undefined' && yylloc) ? (yylloc.first_line || yylineno || 0) : ((typeof yylineno !== 'undefined') ? yylineno : 0);
    var columna = (typeof yylloc !== 'undefined' && yylloc) ? (yylloc.first_column || 0) : 0;
    var lexema = (typeof yytext !== 'undefined') ? yytext : '';
    registrarErrorSintactico(mensaje, lexema, linea, columna);
  }

  parser.parseError = function(str, hash) {
    registrarErrorSintactico(str, hash.text || hash.token, hash.line + 1, hash.loc ? hash.loc.first_column : 0);
    if (!hash.recoverable) {
      throw new Error(str);
    }
  };
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"ranges":true,"yylineno":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* ignorar espacios y saltos */
break;
case 1:/* ignorar invisibles y nbsp */
break;
case 2:/* ignorar comentarios de bloque */
break;
case 3:/* ignorar comentarios de línea */
break;
case 4:return 13;
break;
case 5:return 15;
break;
case 6:return 30;
break;
case 7:return 32;
break;
case 8:return 21;
break;
case 9:return 22;
break;
case 10:return 23;
break;
case 11:return 24;
break;
case 12:return 25;
break;
case 13:return 38;
break;
case 14:return 39;
break;
case 15:return 18;
break;
case 16:return 19;
break;
case 17:return 26;
break;
case 18:return 8;
break;
case 19:return 27;
break;
case 20:return 29;
break;
case 21:return 35;
break;
case 22:return 36;
break;
case 23:return 37;
break;
case 24:return 31;
break;
case 25:return 14;
break;
case 26:return 5;
break;
case 27:
  var linea = (typeof yy_.yylloc !== 'undefined' && yy_.yylloc) ? (yy_.yylloc.first_line || yy_.yylineno || 0) : ((typeof yy_.yylineno !== 'undefined') ? yy_.yylineno : 0);
  var columna = (typeof yy_.yylloc !== 'undefined' && yy_.yylloc) ? (yy_.yylloc.first_column || 0) : 0;
  resgistrarErrorLexico(yy_.yytext, linea, columna);

break;
}
},
rules: [/^(?:\s+)/,/^(?:[\u200B\u200C\u200D\uFEFF\u00A0]+)/,/^(?:\/\*[\s\S]*?\*\/)/,/^(?:#.*)/,/^(?:TABLE\b)/,/^(?:COLUMNS\b)/,/^(?:IN\b)/,/^(?:DELETE\b)/,/^(?:int\b)/,/^(?:float\b)/,/^(?:string\b)/,/^(?:boolean\b)/,/^(?:char\b)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:,)/,/^(?:=)/,/^(?:\.)/,/^(?:;)/,/^(?:\[)/,/^(?:\])/,/^(?:"[^\"]*")/,/^(?:'[^\']')/,/^(?:[0-9]+\.[0-9]+)/,/^(?:[0-9]+)/,/^(?:[a-zA-Z\u00C0-\u017F_][a-zA-Z0-9_\u00C0-\u017F]*)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


export const parser = grammarDB;
export const Parser = grammarDB.Parser;
export function parse(input) {
  return grammarDB.parse(input);
}
